### ISSUE TITLE
Tabs versus spaces in SQL tests

### ISSUE THREAD

**Issue by cramja** [pivotalsoftware/quickstep#22]
@zuyu might have opinions on this. 

In a PR I am going to release today or tomorrow, I am capitalizing SQL keywords in unit tests in the folder parser/tests in preparation for adding unit tests for BLOCKPROPERTIES. Some of these tests (TPCH) have tabs instead of spaces. Is there a reason for this, or can I convert them all to spaces?

--Marc

**Comment by pateljm** [comment]
No reason -- it should be spaces. Go for it. Thanks!

**Comment by zuyu** [comment]
@cramja Get familiar with the code style `https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs`.
