### ISSUE TITLE
New Index Integration

### ISSUE THREAD

**Issue by cramja** [pivotalsoftware/quickstep#24]
Hi everyone, I'm posting because I have a question about what is the easiest way to do a large pull request. @saketj  and I have 2 new IndexSubBlocks ([SMA](https://github.com/pivotalsoftware/quickstep/tree/sma-index-staging), BloomFilter) complete with tests. We want to merge these in the next 3 weeks. These will be quite large PRs (>1000 lines).

I was thinking there might be a couple of viable ways to integrate them.
*  Piece by Piece - That is to say, try to break up the commits in such a way that some of the main functionality can be broken up into smaller, review-able chunks.
*  Code-review style - That is to say, we sit down with a reviewer in person and get suggestions about the to be submitted branch, make enough changes to where the code is almost 100% and then submit a PR with all the functionality.

Personally I like the second solution because human interaction is nice, plus it's likely to be faster for both reviewer and coder.

--Marc

**Comment by hbdeshmukh** [comment]
Me and @cramja had a discussion on this. We will go with the second approach. Marc will send a doodle poll sometime next week, so that if others are interested in knowing about the code, they too can join in.

**Comment by saketj** [comment]
I like the second solution too, will make it faster to review and push changes.

**Comment by pateljm** [comment]
+1 to that. I think there are a few exceptions that we have to make and this is certainly one of them as this is a crucial feature that by design will have to cut across a vast portion of the code. Thanks @cramja @hbdeshmukh and @saketj!
