### ISSUE TITLE
How to display proto message in an optimizer output?

### ISSUE THREAD

**Issue by cramja** [pivotalsoftware/quickstep#32]
**Background**
In an update to the parser/optimizer, we are supporting setting physical properties of blocks. This is done by taking parsed SQL and translating it into a proto message in the the resolver. The proto message is passed down to the operator which finally creates the relation. 

**?**
This question is about the the `getFieldStringItems` method. How should one display a proto message in the field string?

1) One solution I thought of was simply to have it be an attribute with a boolean value, so that the print out would look something like
```
CreateTableStatement[name=foo]
+-HasProto[True]

or
CreateTableStatement[name=foo]
+-HasProto[False]
```

This has the downside of not displaying the details of the proto message.

2) Another solution is to use [Google's protobuf dumping program](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.text_format) to dump the entire message in a field. However, this might make the message look messy.

3) Another solution is to not include any extra output for block properties.

___
I prefer solution (2) because it tells all so to speak. But we might be in favor of the simplicity of (1).

Thoughts?
Marc

**Comment by zuyu** [comment]
Before printing the `proto`, I have a few basic questions:
 1. why the `proto` is the grand truth for the block properties? Do you directly construct the `proto` from the parser results, rather than saving the block property info in some local variables and serializing as `proto` later?
 1. what fields contain in the `proto`?
 1. why need to dump the entire message, rather than display each field one-by-one?

Thanks!

**Comment by cramja** [comment]
To answer your questions:

1) The proto is a convenient and lightweight way to take the 'messy' user input and place it in a machine format. Saving it to local variables would likely mean making logical/physical classes to encapsulate the BlockProperties, which seems cumbersome and redundant when the proto message can hold the needed information.

2) The proto is a [TupleStorageSubBlockDescription](https://github.com/pivotalsoftware/quickstep/blob/master/storage/StorageBlockLayout.proto#L21), with 4 fields describing the physical properties of the block (type-rowstore/columnstore, sort column, etc)

3) Dumping the entire message is fine.

I will go ahead and use the dump everything solution. @zuyu if you agree, go ahead and close this request or we can keep the conversation going.

**Comment by pateljm** [comment]
Hi @cramja: I like solution #2. Go for it. Closing this issue too.

**Comment by zuyu** [comment]
I agree that we need to print out the `proto`, but from the implementation's perspective, not in the way you mentioned to use proto APIs to dump the entire message (the output does not follow our print format).

Instead, I suggest to create a private member function to `stringify` the proto for different `TupleStorageSubBlockDescription`s.

```C++
  switch (proto. sub_block_type()) {
    case TupleStorageSubBlockDescription:: BASIC_COLUMN_STORE: {
      inline_field_names->push_back("tuple_storage_sub_block_type");
      inline_field_values->push_back("kBasicColumnStore");
      inline_field_names->push_back("sort_attribute_id");
      inline_field_values->push_back(
        proto.GetExtension(BasicColumnStoreTupleStorageSubBlockDescription ::sort_attribute_id));
      break;
    }
    default:
      LOG(ERROR) << "Unknown TupleStorageSubBlockType";
  } 
```

Thus creating `BasicColumnStoreTupleStorageSubBlockDescription` looks like
```
CreateTableStatement[name=foo]
+-tuple_storage_sub_block_type[kBasicColumnStore]
+-sort_attribute_id[0]
```
