### ISSUE TITLE
Print Database/Table Schema

### ISSUE THREAD

**Issue by pateljm** [pivotalsoftware/quickstep#52]
We need a command to print the catalogs. Ideally there would be two commands, namely:  
1. `\dt <tablename>` to list the schema of the table. 
2. `\d` to list all the tables in the database. This would be simple loop like 
```
  for (const CatalogRelation &relation : database) {
     cout << relation.name();
     relation.printSchema();  // function created to support the \dt <tablename>
  }
```
We could follow the output format of PostgreSQL.

**Comment by jianqiao** [comment]
We can use the _command_ feature provided by Marc's #49 to achieve this. One choice here: use sqlite style (`.command`) or postgresql style (`\command`)?

**Comment by pateljm** [comment]
@jianqiao @cramja Great idea Jianqiao. I'm partial towards `\command` as that is easier to see v/s `.command` But, we should be consistent. So, if we use `\` as the leading token character here, we should do the same in #49. 

How about you and Marc pick one?

**Comment by cramja** [comment]
#118 Addresses this issue.
